FROM python:3.9

WORKDIR /app

COPY ./backend /app

RUN pip install --upgrade pip
RUN pip install django-environ
RUN pip install -r requirements.txt

RUN python manage.py makemigrations account
RUN python manage.py makemigrations payments
RUN python manage.py makemigrations product

RUN chmod +x /app/start_app.sh

EXPOSE 8000

ENTRYPOINT ["./start_app.sh"]

