version: '3.8'

services:
  backend:
    image: tortiz7/ecommerce-backend-image:latest
    environment:
      - DB_HOST=${rds_endpoint}
      - RUN_MIGRATIONS=${run_migrations}
    ports:
      - "8000:8000"

  frontend:
    image: tortiz7/ecommerce-frontend-image:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
